name: app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter_launcher_icons: "^0.10.0"
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.2.13
  font_awesome_flutter: ^10.2.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
